# rustfmt --print-config current . > .rustfmt.toml
# https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md
max_width = 126
hard_tabs = true
tab_spaces = 3
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Visual"
wrap_comments = false
format_code_in_doc_comments = true
comment_width = 126
normalize_comments = false
normalize_doc_attributes = false
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = true
where_single_line = true
imports_indent = "Visual"
imports_layout = "Mixed"
imports_granularity = "Crate"
reorder_imports = false
reorder_modules = false
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Back"
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
force_multiline_blocks = true
fn_args_layout = "Tall"
brace_style = "PreferSameLine"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
inline_attribute_width = 0
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = true
color = "Auto"
required_version = "1.5.1"
unstable_features = true
