name: Format
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  rust:
    name: rustfmt
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt
          override: false
          allow-downgrade: false

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo

      - name: Check formatting
        shell: bash
        run: cargo +nightly fmt -- --check
